### PR TITLE
python > python3 Ubuntu LTS 20.04.x

### PR DESCRIPTION
**Pull request by francisuk1989**
I am currently using KDE Neon via Ubuntu LTS 20.04 and is currently using python 2.7 by default when calling
`python`

We can fix this by calling; what gives Python 3.8

`python3`

### CODE REVIEW

**Comment by mathiascode** [comment]
actions/setup-python@v2 installs the Python versions specified in the matrix, which in turn overrides the system's `python` command. We don't want to use Ubuntu's default Python versions.

**Comment by mathiascode** [comment]
Hopefully this answered any concerns. I'll close this PR now.

**Comment by francisuk1989** [comment]
Not a problem, It was for Ubuntu LTS release since 20.04.x is here till middle of 2025 as by default Ubuntu is shipping with python 2.7 if using python so using python3 will give python 3.8

**Comment by francisuk1989** [comment]
When building GTK 4 under Ubuntu LTS 20.04.X pycairo gets stuck but fixed by

```
  ERROR: Command errored out with exit status 1:
   command: /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j3qpemb7/pycairo_7944febc6b34439b8dd643cc2460db83/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j3qpemb7/pycairo_7944febc6b34439b8dd643cc2460db83/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jx2e651t
       cwd: /tmp/pip-install-j3qpemb7/pycairo_7944febc6b34439b8dd643cc2460db83/
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/cairo
  copying cairo/__init__.py -> build/lib.linux-x86_64-3.9/cairo
  running build_ext
  building 'cairo._cairo' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/cairo
  gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/Cellar/libffi/3.3_4/include -I/home/linuxbrew/.linuxbrew/Cellar/cairo/1.16.0_7/include/cairo -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.68.4/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.68.4/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.68.4/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/pcre/8.45/include -I/home/linuxbrew/.linuxbrew/Cellar/pixman/0.40.0/include/pixman-1 -I/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.13.1_1/include -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.37/include/uuid -I/home/linuxbrew/.linuxbrew/Cellar/expat/2.4.1/include -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/Cellar/libpng/1.6.37/include/libpng16 -I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include -I/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.14_1/include -I/home/linuxbrew/.linuxbrew/Cellar/libxrender/0.9.10/include -I/home/linuxbrew/.linuxbrew/Cellar/libxext/1.3.4/include -I/home/linuxbrew/.linuxbrew/Cellar/libx11/1.7.2/include -I/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.14_1/include -I/home/linuxbrew/.linuxbrew/Cellar/libxau/1.0.9/include -I/home/linuxbrew/.linuxbrew/Cellar/libxdmcp/1.1.3/include -I/home/linuxbrew/.linuxbrew/Cellar/xorgproto/2021.4/include -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c cairo/cairomodule.c -o build/temp.linux-x86_64-3.9/cairo/cairomodule.o
  error: command 'gcc-5' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
```


https://askubuntu.com/questions/1316961/experiencing-gcc-5-failure-running-poetry-install-on-ubuntu-20-04
followed by
pip3 install p5py
pip3 install PEP517
pip3 install netifaces
and then install pycairo
pip3 install pycairo

**Pull request closed without merging**
