### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [nicotine-plus/nicotine-plus](https://hosted.weblate.org/projects/nicotine-plus/nicotine-plus/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by slook** [comment]
@mathiascode @hboetes The test failure error "Python format string does not match source" seems to be concerning... 127 affected strings for all languages, see link:

https://hosted.weblate.org/checks/python_format/nicotine-plus/nicotine-plus/

For example "Following format strings are missing: %s" surely this would lead to a Critical Error at runtime? Unless the failed translations fall back to English in this case... I'm not sure how it works.

**Comment by mathiascode** [comment]
Those strings are marked as "Needs editing" (fuzzy), so they won't be included. We have a unit test that catches these kind of errors in finished strings.

**Comment by slook** [comment]
Cool sweet, thanks for clarifying that makes sense.

Has the Italian translator been alerted that a release is imminent?

**Comment by hboetes** [comment]
> Has the Italian translator been notified that a release is imminent?

For now, there is no mechanism to inform our translators of upcoming releases.

**Comment by slook** [comment]
@M0Rf30 Just to let you know release to Stable will be very soon if you wanted to update your translations by any method you prefer. Thank you for all your input during this development cycle your efforts are much appreciated :)

**Comment by hboetes** [comment]
I can find their weblate usernames, but with that I can't even email them. So, that's basically anonymous.

**Comment by slook** [comment]
That's okay their email addresses cannot be posted without permission anyway.

**Comment by hboetes** [comment]
And I don't think it's up to us to add their names to the translators list, if it's not their wish. It's in the documentation how they can add it, if they wish it.
I could add an announcement on weblate, inviting them to share their details, so we can inform them of upcoming releases and add the information they want to share with the contributors list.

**Comment by slook** [comment]
That sounds like a great idea. With all the effort that's been put in, it would be a shame for them to not get the credit they deserve.

**Comment by hboetes** [comment]
I just figured out how to send notifications. If their settings are correct, they should receive an email from Weblate with the following message:

> On behalf of the other developers of Nicotine+ and me, I'd like to thank all translation contributors for their incredible effort.
>
> We are getting close to the next release of nicotine+-3.2.0 and have frozen all translation strings, so no more unexpected changes will come from us. We hope you can have a look at the status of your preferred language and see if there is anything left to do.
> As a thank-you, we invite you to add yourself to the contributor list, see:
>   https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TRANSLATIONS.md#adding-yourself-to-translators
>
> If you are unsure of how to that or don't want to set up a github account, please send me an email at <redacted email> and I'll add you to the list.

**Pull request merged**
