### PR TITLE
Update NEWS

### PR DESCRIPTION
**Pull request by mathiascode**
Anything I forgot to include?

### CODE REVIEW

**Comment by kiplingw** [comment]
Well done Mat.

**Comment by mathiascode** [comment]
And many, many thanks to @lene, @droserasprout and everyone else who have contributed so far. Without them, 2.0 would not become a reality.

**Comment by mathiascode** [comment]
Might be worth reaching out to upstreams (Debian, Fedora) regarding inclusion again, and potential patches we could merge in the process.

**Comment by kiplingw** [comment]
I've just emailed Debian's downstream package maintainer listed [here](https://tracker.debian.org/pkg/nicotine), Josselin Mouette.

**Comment by mathiascode** [comment]
Thanks! I've sent an email to melmorabity, the maintainer of the Fedora package.

**Comment by kiplingw** [comment]
And in case anyone is interested, you can see Debian's Popularity Contest (popcon) graph for the old package [here](https://qa.debian.org/popcon.php?package=nicotine).

**Comment by mathiascode** [comment]
@kiplingw Have you heard anything back from Josselin?

**Comment by kiplingw** [comment]
Sadly not yet.

**Comment by kiplingw** [comment]
So it looks like the previous downstream Debian package maintainer is MIA and has been for over a year. The package was orphaned and removed from the repository. There's steps to get it back in though that can be taken. I've emailed Moritz on [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930137) thread.

**Comment by pabs3** [comment]
In case there is someone interested to bring the package back into the Debian repository, please take a look at these links:

https://mentors.debian.net/intro-maintainers
https://www.debian.org/doc/manuals/developers-reference/pkgs.html#reintroducing-pkgs

**Pull request merged**
