### PR TITLE
Make Nicotine+ icon crisper at smaller sizes

### PR DESCRIPTION
**Pull request by mathiascode**
Make the main Nicotine+ icon crisp at 32x32 and above, instead of just 128x128.

Preview

### CODE REVIEW

**Comment by mathiascode** [comment]
@kiplingw corrected icon for https://github.com/Nicotine-Plus

org nicotine_plus Nicotine256

**Comment by kiplingw** [comment]
Looks good @mathiascode. You should have all the permission bits set that you need to update it.

**Comment by mathiascode** [comment]
Currently don't have permissions. I need to have owner status in the Nicotine-Plus GitHub organization in order to change details such as the image.

**Comment by eLvErDe** [comment]
I'll fix that by the end of the week

**Comment by mathiascode** [comment]
Any update on this?

**Pull request merged**
