### PR TITLE
Various Flake8 fixes

### PR DESCRIPTION
**Pull request by r900**
Fixes the most annoying errors when running the source code through flake8.
All but one E999 errors are gone, I didn't look into how to fix this yet (`pynicotine/slskproto.py`, line 998).
AFAICT none of the changes should affect functionality, so far it runs nicely on my machine.

### CODE REVIEW

**Comment by eLvErDe** [comment]
Hi, did you try running it with python 3 After these changes ?

**Comment by r900** [comment]
yes, but fails. ;(
i guess this will need quite some changes, the usual unicode/str/bytes fun..
that being said if there is a python3 port in progress i'd like to chip in a bit of my time.

i also realized that master is also behind develop, so i adjusted the PR. not as clean as i'd like it to be, though...

**Comment by kiplingw** [comment]
@r900, are you comfortable with the PR and ready for it to be merged?

**Comment by r900** [comment]
@kiplingw TBH i have not looked into this for months. pretty much gave up when realizing that switching to python3 also means switching to gtk3 - which i have no experience with, and not much spare time to look into right now.

that being said - this weekend i can look into the changes i made back then, and see if they still make sense to me now.

**Comment by kiplingw** [comment]
Ok thanks @r900. I'm looking forward to merging your PR as soon as you are comfortable so that everyone can enjoy your work. There are a lot of people who use the daily PPA, but we won't merge your PR until you are ready.

**Comment by r900** [comment]
@kiplingw thanks for your patience :) so after looking through this again i think it should still not break anything while making flake8 happy/happier, so from my side it's good to go

**Pull request merged**
