### PR TITLE
Rename human

### PR DESCRIPTION
**Pull request by hboetes**
I propose renaming the following functions and variable, to make their function clearer:

humanize→human_number
human_length→human_time
h_length→h_time

Which I executed with the following commands:
```
cd pynicotine
sed -i 's|humanize|human_number|' $(ag -l humanize|ag -v config.py)
sed -i 's|human_length|human_time|' $(ag -l human_length)
sed -i 's|h_length|h_time|' $(ag -l h_length)
```

### CODE REVIEW

**Comment by slook** [comment]
Whilst your suggested names make sense, it is likely that user's custom plugins will break as a result of this change.

The confusion isn't large enough to warrant these breaking changes.

**Comment by hboetes** [comment]
I've never heard of somebody writing a custom plugin. %-)

**Comment by slook** [comment]
We have a plugin system, so it can be assumed that people use it and the functions in utils.py are common in those plugins.

For example, there is a plugin called NoEmbed Info that is similar to the YouTube Info plugin, that would be broken by these changes.

**Comment by mathiascode** [comment]
I don't think these function names are bad enough to warrant a name change right now.

**Comment by hboetes** [comment]
ok, no worries

**Pull request closed without merging**
