### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Nicotine+/nicotine-plus](https://hosted.weblate.org/projects/nicotine-plus/nicotine-plus/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by slook — CHANGES_REQUESTED** [review]
All the changed strings should be **T**itle **C**ase.

**Comment by mathiascode** [comment]
> All the changed strings should be **T**itle **C**ase.

Depends on the language. Title case isn't a thing in many languages (but please confirm if applies in this case or not).

**Comment by slook** [comment]
From what I understand Title Case isn't really a thing in any language, since it's not considered proper form unless the words refer to a given name of a person or entity. Nevertheless, it's more of a graphical design/typesetting thing.

I don't think there is a Right Way™ of doing button labels, but the main buttons at the top the main window do also act as headings for the main functions in the application.

**Comment by mathiascode** [comment]
Those guidelines are written with English in mind (they don't make any sense in my primary language). We should be consistent with other applications/the OS, as well as expectations in the language.

I've checked, and Latvian translations in other applications use sentence case, so this change is fine.

**Pull request merged**
