### PR TITLE
declunkify

### PR DESCRIPTION
**Pull request by hboetes**

### CODE REVIEW

**Comment by mathiascode** [comment]
Could you make the same changes to the strings in uploads.ui as well?

**Comment by hboetes** [comment]
> Could you make the same changes to the strings in uploads.ui as well?

Yes! They are surprisingly similar. :-)

**Comment by slook** [comment]
I don't think we need two buttons, the menu one is enough imo. See https://github.com/nicotine-plus/nicotine-plus/pull/1902

**Comment by mathiascode** [comment]
We can continue the discussion in #1902

**Pull request merged**
