### PR TITLE
Update Italian localization

### PR DESCRIPTION
**Pull request by M0Rf30**
As in title.
Regards

### CODE REVIEW

**Comment by mathiascode** [comment]
Thanks! One question, how do you generate the nicotine.pot file?

**Comment by M0Rf30** [comment]
As you previously suggested with:
`python3 setup.py update_pot`

**Comment by mathiascode** [comment]
That's fine. I suppose some subtle system differences change the order of the strings somehow.

**Comment by mathiascode** [comment]
The strings should be sorted in the latest commit. Can you check if `python3 setup.py update_pot` yields the same result as the current `nicotine.pot` file?

**Comment by M0Rf30** [comment]
Ok I fetched latest commits, update the pot file and here the diff after a test commit
```
-"POT-Creation-Date: 2021-05-18 18:07+0300\n"
+"POT-Creation-Date: 2021-05-18 17:17+0200\n"
```
So it should be ok

**Pull request merged**
