### PR TITLE
Rework custom icon theme system

### PR DESCRIPTION
**Pull request by mathiascode**
- Stop using GIcon to improve scrolling performance in treeviews
- Allow changing icon theme without restarting Nicotine+

### CODE REVIEW

**Comment by slook** [comment]
The tray icon and flags appear correctly (btw i'm still testing with Debian 9 / Python 3.5 GTK 3.22.11 for another week or two.)

**Comment by mathiascode** [comment]
Can you compare scrolling smoothness of the user list in the nicotine room? This change doesn't really affect CPU usage, and I'm not sure we can do anything about it, but it should result in slightly higher FPS in lists with many status icons.

**Comment by mathiascode** [comment]
> The scrolling FPS was never an issue for me

I believe it's only noticeable if the system is under heavy load.

> What about skipping the getting of icon if the Status or Country icon column(s) is not visible?

How would this make a difference? The CPU usage when scrolling is high no matter which columns are visible.

**Comment by slook** [comment]
How would this make a difference?

Logically thinking, scrolling should be lighter on CPU if there are no image render columns, but this isn't the case. It is my guess that even an invisible column(s) might consume CPU.

**Comment by mathiascode** [comment]
I don't believe it's the icons that consume CPU here. It happens in the transfer views as well. Some of it is due to GTK 3 not being hardware accelerated, GTK 4 uses less CPU.

**Pull request merged**
