### PR TITLE
Version 2.1.1

### PR DESCRIPTION
**Pull request by mathiascode**
2.1.1 needs some final testing, but is essentially ready.

### CODE REVIEW

**Comment by kiplingw** [comment]
If you don't have anything else on the agenda for the near future, I'm happy to merge this.

**Comment by mathiascode** [comment]
Nothing specific in the pipeline right now. I'm leaning towards having a few smaller, more focused releases out instead of the previous massive ones, mainly to make life easier when testing and debugging.

**Comment by kiplingw** [comment]
Then in that case I'm happy to merge.

**Comment by mathiascode** [comment]
sdist: [nicotine-2.1.1.tar.gz](https://github.com/Nicotine-Plus/nicotine-plus/files/5287799/nicotine-2.1.1.tar.gz)

Windows builds in progress.

**Pull request merged**
