### PR TITLE
Slightly increase border radius of full-size Nicotine+ icon

### PR DESCRIPTION
**Pull request by mathiascode**
Make the rounded corners a bit more distinguishable if the icon is scaled down.

Updated assets:

- GitHub organization
icon512

- Launchpad team:
icon14
icon64
icon192

### CODE REVIEW

**Comment by mathiascode** [comment]
@kiplingw Could you set these new icons for the Nicotine+ GitHub organization and Launchpad team page? I don't have permissions to do that myself. Thanks!

**Comment by kiplingw** [comment]
@mathiascode, can you let me know what permission bits you need set so you can do this?

**Comment by mathiascode** [comment]
If I remember correctly, only owners of a Github organization can do it. As for Launchpad, it seems like I can update the icon now that I'm an administrator.

**Comment by kiplingw** [comment]
Just set your admin bit and updated the image.

**Comment by mathiascode** [comment]
Thanks, but I was referring to the icon on this page specifically (not to be confused with the repository image): https://github.com/Nicotine-Plus

**Comment by kiplingw** [comment]
Done.

**Pull request merged**
