### PR TITLE
Allow showing buddy-only shares to everyone

### LINKED ISSUE #1870: show files to all but locked
im confused i cant seem to work out how to make all my shares public but not downloadable unless the user is added to my Buddie List, people who are not on my list cannot view anything im sharing only my buddie list can

### PR DESCRIPTION
**Pull request by mathiascode**
Implements the plan described in https://github.com/nicotine-plus/nicotine-plus/issues/1870#issuecomment-1604290920

Closes #1870 

Seems to be working, but I wrote this yesterday while very tired, so variable names and code quality could perhaps be improved.

### CODE REVIEW

**Comment by slook** [comment]
I don't think it will be satisfactory enough for this to be a global setting. It is inevitably going to be required for this to be defined for each configured shared folder.

**Comment by mathiascode** [comment]
I have no desire to work on groups and the performance and UI challenges it would bring in the near future. We either add this solution now, or wait another few years for something more granular like SoulseekQt has.

This PR addresses what was asked for in the first post in the issue report. For anything else, we have https://github.com/nicotine-plus/nicotine-plus/issues/2093.

**Comment by slook** [comment]
It seems non-sensical to introduce an option that has planned obsolescence.

However, I can appreciate that it is difficult to see a more linear development path at this time.

**Comment by mathiascode** [comment]
I received more requests about adding this as-is, so I've decided to finish this PR. The changes to the db files provide some nice reductions in memory and disk space usage anyway, due to no longer duplicating public shares in the buddy*.db files.

**Pull request closed without merging**
