### PR TITLE
Add checks for settings window when updating config

### PR DESCRIPTION
**Pull request by mathiascode**
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/228

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @mathiascode. I'm going to hold off on merging this until #228 is fixed. Right now it's useful for if this bug is preserved for the time being to verify #228's patch worked.

**Comment by mathiascode** [comment]
That's fine :)

**Comment by mathiascode** [comment]
@kiplingw The CI test should now be working

**Comment by kiplingw** [comment]
Thanks for fixing the test, but we need it to fail for the time being to ensure the test harness detects the failure. Otherwise if other tests fail, they might potentially get silently ignored. If you don't mind I'll wait until @lene takes a look at the test harness issue.

**Comment by mathiascode** [comment]
Seems to be doing its job: https://github.com/Nicotine-Plus/nicotine-plus/pull/234
Unless I'm misunderstanding something?

**Comment by lene** [comment]
Sorry, I lost track of what's going on. Is anything still needed and if so, what exactly?

**Pull request merged**
