### PR TITLE
Add option to show locked/privately shared files in search results

### PR DESCRIPTION
**Pull request by mathiascode**
For the sake of transparency, I've added the option to show privately shared/locked files from other clients in search results. Since this is a controversial Soulseek feature, these files will not appear in results unless explicitly enabled in the search preferences.

For more information, see: https://groups.google.com/g/soulseek-discussion/c/vAnknGtihxg/m/pU2ItYSMAQAJ

### CODE REVIEW

**Comment by BachoSeven** [comment]
Is there any visual indication that the locked files are such from the search interface?

**Comment by mathiascode** [comment]
Such files are currently prefixed with "[PRIVATE FILE]". A padlock icon would probably look better, but I had issues getting it working for now.

**Comment by BachoSeven** [comment]
Hei, I thought I'd mention it here first but you might want me to post this as a separate issue:
two times out of two, while searching for a file which I know to be locked and/or interacting with an user whom I know has all locked files(`CaptainNoFuture`), I've had the log window flooded with this messages:
```
22:06:19 Peer init message type 4 size 4 contents bytearray(b'\x04\x00\x00\x00') unknown
```
So I assumed it's related to this...

**Comment by mathiascode** [comment]
@BachoSeven Is this still happening on the latest master?

**Comment by mathiascode** [comment]
I've pushed more changes since my last comment.

**Comment by BachoSeven** [comment]
Sorry, I'll try this out now

**Comment by BachoSeven** [comment]
It seems to be fixed, I successfully found the locked file(which shows up as expected with `[PRIVATE FILE]`, and browsing the user doesn't flood the logs anymore. Thanks for the fix

**Comment by BachoSeven** [comment]
btw, browsing the user doesn't show the private/locked files, which is intentional right? not sure if there's a use case for wanting to turn that on through an option as well, but it might be useful for someone, just throwing the idea out there.

**Comment by mathiascode** [comment]
> btw, browsing the user doesn't show the private/locked files, which is intentional right? not sure if there's a use case for wanting to turn that on through an option as well, but it might be useful for someone, just throwing the idea out there.

I've now implemented this.

**Pull request merged**
