### PR TITLE
Minor Flatpak corrections

### PR DESCRIPTION
**Pull request by mathiascode**
- Allow notifications
- Allow sounds to be played
- Allow tray icon to appear

Need to look into:
- Loading resources properly (plugins, tray icons and sounds don't load atm)

Will not fix for 2.0.0:
- Can't open files in media player
- Can't get title of currently playing song

### CODE REVIEW

**Comment by mathiascode** [comment]
Having some issues with sys.prefix being wrong (/usr instead of /app), but I'll check if it's just an issue with my environment when submitting to Flatpak. This can be merged.

**Comment by mathiascode** [comment]
Splitting out the irrelevant commits into a separate PR.

**Comment by kiplingw** [comment]
Ready?

**Comment by mathiascode** [comment]
Removing files from here in favor of https://github.com/flathub/flathub/pull/1585

**Pull request closed without merging**
