### PR TITLE
Add option to wait for uploads to finish when quitting

### LINKED ISSUE #885: Finish running transfers and quit
Maybe it would be nice if there was an option to allow the currently running uploads to finish and then quit?

### PR DESCRIPTION
**Pull request by mathiascode**
Current behavior in this PR:
- Quitting Nicotine+ from the tray icon or operating system's quit menu item exits immediately, since showing confirmation dialogs here is not common behavior for applications (and users have requested to not show them here before)
- Quitting inside Nicotine+ (Menu -> Quit or Ctrl+Q) always shows a confirmation dialog, with an option to finish uploads before exiting. As before, the Ctrl+Alt+Q shortcut can be used to quit immediately.
- Closing the main window (using the X button or Alt+F4) follows the preference set in Preferences -> User Interface (Quit, show confirmation dialog or run in background)

Closes #885

### CODE REVIEW

**Comment by mathiascode** [comment]
Fixed the unit test.

**Comment by mathiascode** [comment]
There are probably improvements that could be made, perhaps we should e.g. remember the last state of the checkbox in future sessions, but I'll merge this now and wait for feedback.

**Comment by slook** [comment]
On Menu -> Quit -> Quit

```
Nicotine+ Version: 3.3.0.dev5
GTK Version: 3.24.24
Python Version: 3.9.2 (linux)

Type: <class 'TypeError'>
Value: GObject.emit needs at least one arg
Traceback:   File "/home/user/Git/mathiascode/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 1320, in on_toggle_status
    self.application.lookup_action("away").emit()
```

**Comment by mathiascode** [comment]
Fixed in https://github.com/nicotine-plus/nicotine-plus/commit/1c620c5afa8c98f6005a194eeffadb2085267c7d

**Comment by slook** [comment]
When I upload a file to myself, and choose Quit with Allow uploads to finish, the status remains on "Quitting..." and the program stays running. I expect it probably works okay for uploads to users other than self.

**Comment by slook** [comment]
No, it still doesn't exit.

**Comment by mathiascode** [comment]
> No, it still doesn't exit after the last upload is finished.

Please provide detailed steps to reproduce this issue.

**Comment by mathiascode** [comment]
Ok, seems to be an issue exclusive to the GTK 3 version.

**Comment by slook** [comment]
GTK 3.24.24

**Pull request merged**
