### PR TITLE
settings/uploads.ui: improve a few strings

### PR DESCRIPTION
**Pull request by mathiascode**
Replaces #1936

Upload prefs

### CODE REVIEW

**Comment by mathiascode** [comment]
@hboetes Thoughts?

**Comment by hboetes** [comment]
I'd remove the word 'use' so:

- upload speed limit
- alternative upload speed limit

And I think putting the buddy checkboxes as the last item of the paragraph looks better, since they are the exception:

- Upload queue type
- Allocate upload slots until total speed reaches (KiB/s):
- Fixed number of upload slots:
- Prioritize Buddies

- Each user may queue a maximum of either:
- Limits do not apply to buddies.

And I left a few words out on purpose.

**Comment by mathiascode** [comment]
> * Prioritize Buddies

Needs to mention that the option prioritizes every buddy, i.e. overrides the preference in the buddy list.

**Comment by hboetes** [comment]
> > * Prioritize Buddies
> 
> Needs to mention that the option prioritizes every buddy, i.e. overrides the preference in the buddy list.

OK, then it should be "prioritize all buddies" indeed.

**Comment by mathiascode** [comment]
Made some changes:
Upload preferences

**Comment by hboetes** [comment]
Looking good!  😎

**Pull request merged**
