### PR TITLE
Version 2.1.2

### PR DESCRIPTION
**Pull request by mathiascode**
I think we're ready for a new release.

### CODE REVIEW

**Comment by mathiascode** [comment]
Postponing this a bit. I have a macOS VM set up now, so there will be some fixes coming up.

**Comment by mathiascode** [comment]
Ready.

**Comment by kiplingw** [comment]
Thanks Mathias. Can you confirm you've ran it through Autopkgtest on focal, groovy, etc?

**Comment by mathiascode** [comment]
I can confirm.

**Comment by kiplingw** [comment]
@mathiascode, can you update the list of fixed bugs? I'll merge later this afternoon.

**Comment by mathiascode** [comment]
I'll update the release date in the readme, then you can merge.

**Comment by mathiascode** [comment]
https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/302734514
[nicotine-2.1.2.tar.gz](https://github.com/Nicotine-Plus/nicotine-plus/files/5366950/nicotine-2.1.2.tar.gz)

**Pull request merged**
