### PR TITLE
downloads.py: delete stale incomplete downloads

### PR DESCRIPTION
**Pull request by mathiascode**
Delete incomplete download files that are no longer in the list.

### CODE REVIEW

**Comment by slook** [comment]
I can envisage a scenario that could make the program very slow to quit while gathering `allowed_incomplete_file_paths`, so it would be better to tidy up as we go... This should be better handled in `_clear_transfer()`.

**Comment by mathiascode** [comment]
> I can envisage a scenario that could make the program very slow to quit while gathering `allowed_incomplete_file_paths`

I restored the `current_byte_offset` check (forgot this is why I added it in the first place two months ago).

The reason I want to do this on shutdown is to give some room for error, if someone is halfway through a download and removes it by mistake, or wants to change the download folder path. In the future, we will hopefully have better tools/protections for that.

**Comment by slook** [comment]
I agree it is convenient that re-adding an accidentally deleted incomplete download results in resuming it from existing data.

**Comment by mathiascode** [comment]
Besides, we have to use this approach to remove incomplete files that were removed from the list long ago.

**Pull request merged**
