### PR TITLE
Version 2.1.0

### PR DESCRIPTION
**Pull request by mathiascode**
Opening this PR in preparation for 2.1.0, which is right around the corner now.

Closes https://github.com/Nicotine-Plus/nicotine-plus/issues/504

### CODE REVIEW

**Comment by mathiascode** [comment]
Now that https://github.com/Nicotine-Plus/nicotine-plus/pull/655 has been merged, things are shaping up really well for a 2.1.0 release. I've done some testing on the Windows and Flatpak builds, and haven't noticed any other issues so far. @hboetes has been running master for well over 24 hours now, and resource usage has remained stable.

**Comment by hboetes** [comment]
Not only that, the load has been much reduced, compared to 2.0.1, about a factor 5!
The visible difference between 1.4.3 and 2.0.1 is much smaller, but the difference on the inside is just as big.

```
% git diff 2.0.1|wc -l
  115010                                                                                                                                                         
% git diff 1.4.1 2.0.1|wc -l
  157880
```

**Comment by mathiascode** [comment]
@kiplingw Feel free to merge and tag a new release if there are no objections.

**Comment by kiplingw** [comment]
Done. Please generate the Windows installers when ready and I will add them to the release.

**Comment by mathiascode** [comment]
Thanks, will do! You'll have to change the release title to "2.1.0", since the update checker still grabs the version from the title in Nicotine+ 2.0.1 and below.

**Comment by kiplingw** [comment]
Done. While you're at it, also verify the OS X image is available too and I will upload it.

**Comment by mathiascode** [comment]
sdist: https://github.com/mathiascode/nicotine-plus/blob/exe/nicotine-2.1.0.tar.gz
win 32-bit: https://github.com/mathiascode/nicotine-plus/blob/exe/files/windows/Nicotine+-2.1.0-i686.exe?raw=true
win 64-bit: https://github.com/mathiascode/nicotine-plus/blob/exe/files/windows/Nicotine+-2.1.0-x86_64.exe?raw=true

I'm not sure if I want to mark the macOS build as stable yet, since nobody has verified that they work properly yet.

**Comment by kiplingw** [comment]
Uploaded.

Also looks like the update checker isn't working. It should have seen the new stable tag as newer than the development release. That is, 2.1.0 > 2.1.0.dev1.

**Pull request merged**
