### PR TITLE
Implement event emitter for communication between components

### PR DESCRIPTION
**Pull request by mathiascode**
Instead of the core directly calling methods in the frontend, the frontend can listen to events emitted by the core.

As a result of this:

- The core is completely isolated from the frontend, preventing developers from accidentally depending on frontend code in the core
- The frontend no longer needs to implement every callback in specific classes, improving maintainability and allowing for more flexibility when structuring the code

### CODE REVIEW

**Comment by slook** [comment]
Invisible Downloads / Uploads histories, and Private Chat tabs not loaded.

**Comment by mathiascode** [comment]
Transfers and chats haven't been fully migrated to the event system yet.

**Comment by slook** [comment]
It does load up alright now

**Comment by mathiascode** [comment]
Here goes nothing!

**Pull request merged**
