### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Nicotine+/nicotine-plus](https://hosted.weblate.org/projects/nicotine-plus/nicotine-plus/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by slook** [comment]
@hboetes There is some kind of error (for N+ 3.2.9, unrelated to this PR) in the Debian packing, see link...

- https://tracker.debian.org/pkg/nicotine

... wherein it says:

> action needed
> Issues found with some translations (Priority: low)
>
> Automatic checks made by the Debian l10n team found some issues with the translations contained in this package. You should check the [l10n status report](https://i18n.debian.org/l10n-pkg-status/n/nicotine.html) for more information.
> 
> Issues can be things such as missing translations, problematic translated strings, outdated PO files, unknown languages, etc.

----

- https://i18n.debian.org/l10n-pkg-status/n/nicotine.html

> The following errors were found in nicotine 's PO files:
> `gettext: po/zh_Hans.po: can't guess language`
> Please ask the translator (identified by the Last-Translator field in the PO file), the language team (identified by the Language-Team field) or [debian-i18n](mailto:debian-i18n@debian.org) for a fix.

**Comment by hboetes** [comment]
> The following errors were found in nicotine 's PO files:
> `gettext: po/zh_Hans.po: can't guess language`

Makes sense, the file does not exist: https://github.com/nicotine-plus/nicotine-plus/tree/3.2.9/po

Though it is mentioned in the source:
```
nicotine@bran ~/src/nicotine-plus % git checkout 3.2.9
HEAD is now at 93b070cc2 Version 3.2.9 (#2429)
nicotine@bran ~/src/nicotine-plus % grep zh_hans
data/org.nicotine_plus.Nicotine.appdata.xml
  <name xml:lang="zh_Hans">Nicotine+</name>
  <summary xml:lang="zh_Hans">Soulseek ç½ç»çå¾å½¢å®¢æ·ç«¯</summary>
    <p xml:lang="zh_Hans">Nicotine+ æ¯ Soulseek ç¹å¯¹ç¹ç½ç»çå¾å½¢å®¢æ·ç«¯ã</p>
    <p xml:lang="zh_Hans">Nicotine+ æ¨å¨æä¸ºä»¤äººæå¿«ãåè´¹åå¼æº (FOSS) çå®æ¹ Soulseek å®¢æ·ç«¯æ¿ä»£åï¼æä¾é¢å¤çåè½ï¼å¹¶ä¸ Soulseek åè®®ä¿æåæ­¥ã</p>
  <developer_name xml:lang="zh_Hans">Nicotine+å¢é</developer_name>

po/zh_CN.po
"nicotine-plus/nicotine-plus/zh_Hans/>\n"
```

@mathiascode did we forget something?

**Comment by slook** [comment]
>> `gettext: po/zh_Hans.po: can't guess language`

> po/zh_CN.po

filename mismatch

**Comment by mathiascode** [comment]
> @mathiascode did we forget something?

The language code was incorrect before, and corrected in 3.2.9: https://github.com/nicotine-plus/nicotine-plus/commit/858f9677ec755c1e72f0b316800d627acf99d250

I believe the warning should go away once 3.2.9 has been fully accepted and propagated everywhere.

**Pull request merged**
