### PR TITLE
Add "Group by folder" option

### PR DESCRIPTION
**Pull request by mathiascode**
Replaces the old "Group by users" feature.

Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/17

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks Mathias. Is this ready?

**Comment by mathiascode** [comment]
Still some minor things to do in the downloads/uploads view.

**Comment by mathiascode** [comment]
Will probably target this for 2.0.0 after all.

**Comment by hboetes** [comment]
I think this feature would be very welcome for 2.0.0
Nobody expects a perfect .0.0 release and I haven't found any annoying problems. This is a huge step forward, one that will for slsk itself to start moving again.

**Comment by mathiascode** [comment]
I agree. Marking this as ready for merge, since no issues seem to have popped up.

**Pull request merged**
