### PR TITLE
Add initial documentation for maintainers

### PR DESCRIPTION
**Pull request by mathiascode**
Initial work on documentation for Nicotine+ maintainers, to increase the bus factor and help myself remember things.

### CODE REVIEW

**Comment by mathiascode** [comment]
@kiplingw thoughts so far?

**Comment by kiplingw** [comment]
Hmm, some overlap with `ReadMe.md`. Specifically on the unit testing and CI stuff. Maybe all maintainer related stuff should be moved into your new file?

**Comment by mathiascode** [comment]
That's true, perhaps this file could be intended for both maintainers and developers/code contributors? Some of the information would certainly be important for someone thinking about diving into the code.

**Comment by kiplingw** [comment]
I agree. I just don't want redundant information that has to be maintained in two places. Maybe you could move everything maintainer related into the new file, and leave a note in the `ReadMe.md` where maintainers should be looking?

**Comment by mathiascode** [comment]
Sounds good to me.

**Comment by mathiascode** [comment]
Updated. Anything you would like me to cover in the file?

**Comment by kiplingw** [comment]
Looks good. Also make sure the Debian toolchain detects all the documentation files correctly and installs them wherever they should go. I think this is somewhere in `/usr/share/...`.

**Comment by mathiascode** [comment]
Thanks. This is taken care of by distutils: https://github.com/Nicotine-Plus/nicotine-plus/blob/master/setup.py#L87-L103

**Pull request merged**
