### PR TITLE
Column fixes

### PR DESCRIPTION
**Pull request by mathiascode**
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/79
Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/8

A few ranges were incorrect, causing the visibility status to not be set for the last column.

### CODE REVIEW

**Comment by 0pLuS0** [comment]
Well it's nice to see development is back, hope there will be a new version soon.

When gfarmerfr picked up the project, I was hoping back then, these things would of been done, and we'd be on several versions later.

Nicotine is such a great app, so sad it went by the side, I truly hope it's coming back...

THANKS

**Comment by 0pLuS0** [comment]
@mathiascode 

If you remember, I just cloned your Repo today;

git clone -b chatfixes https://github.com/mathiascode/nicotine-plus.git

Are these changes already in the source, or for later? Because on this source I cloned today, I still see this issue...

THANKS

**Comment by mathiascode** [comment]
@0pLuS0 They are now in master.

**Comment by 0pLuS0** [comment]
Ok, I just cloned it again and now it works!

THANKS

**Comment by mathiascode** [comment]
Nice! Report all issues in this main repo.

**Comment by 0pLuS0** [comment]
Ok...

THANKS

**Comment by 0pLuS0** [comment]
@mathiascode 

I'm not using from your repo, I just cloned from;

```https://github.com/Nicotine-Plus/nicotine-plus.git```

About a week ago, and I still see the same problem, but this might only be happening under ```Search Files```,  the other sections I have not had time to check them.

In ```Search Files```, if I spread apart the sections; User, Filename, Size... etc... Then I do a new Search, these sections move back closer together, they are not staying where I place them.

Hmm

**Comment by mathiascode** [comment]
I can't reproduce. Do the columns move back to their initial position, or just slightly closer than before?

Please don't use my repo anymore, it's outdated. Use the main https://github.com/Nicotine-Plus/nicotine-plus.git in the future.

**Comment by 0pLuS0** [comment]
Ok I'll use the Main Repo, I just cloned from it now, and it's working...

Hmm odd

THANKS

**Pull request merged**
