### PR TITLE
Use PyGObject Notify

### PR DESCRIPTION
**Pull request by mathiascode**
Get rid of pynotify.

### CODE REVIEW

**Comment by kiplingw** [comment]
Thank you @mathiascode. Don't forget to update `debian/control` whenever updating dependencies if necessary.

**Comment by mathiascode** [comment]
I realised I forgot to remove python3-notify2 from the dependency list. Could you remove it (so we avoid unnecessary PRs)?

**Comment by kiplingw** [comment]
Done.

**Comment by kiplingw** [comment]
It looks like this [broke](https://launchpadlibrarian.net/480380179/buildlog_ubuntu-focal-amd64.nicotine_1.4.3-202005190216~ubuntu20.04.1_BUILDING.txt.gz) the package. Always remember to try building the source package and running it through autopkgtest before pushing. It has saved me many times.

**Pull request merged**
