### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by mathiascode**
- Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/146
- Fixes https://github.com/Nicotine-Plus/nicotine-plus/issues/145
- Fixes the character issue in https://github.com/Nicotine-Plus/nicotine-plus/issues/144
- UI spacing fixes in a few locations
- Adds a button to reset/remove your user pic
- Removed plugin install/update UI, since there was functionality coded for them

### CODE REVIEW

**Comment by zniavre** [comment]
i guess something wrong with exit dialog window, i saw you hav made mods with this one, so ...

it quits without the exit dialog (choice to:  exit or send to tray  or wathever)

**Comment by zniavre** [comment]
there is a problem with exit dialog > what i remember before via menu > File > Exit ( ctrl-q) it gave the exit dialog to choose 3 alternatives (send2tray/exit/cancel) since commit150 it quit without dialog 

but using window manager quit button launch the dialog window

**Comment by mathiascode** [comment]
@zniavre For me, Menu > File > Exit (ctrl-q) quits without the dialog in the GTK2 version too.

**Comment by zniavre** [comment]
sorry for that ...

**Pull request merged**
