### PR TITLE
Fix issue where no search requests were processed except our own

### PR DESCRIPTION
**Pull request by mathiascode**
Here comes 2.0.1...

### CODE REVIEW

**Comment by mathiascode** [comment]
2.0.1 Windows installer: https://github.com/mathiascode/nicotine-plus/blob/62809445da1e0a5f4c8a2da440331b1c65d86ed8/files/windows/Nicotine+-2.0.1.exe?raw=true

I suggest releasing 2.0.1 asap, this bug is quite harmful for the health of the network.

**Comment by kiplingw** [comment]
@mathiascode, if you can resolve this conflict I will merge.

**Comment by kiplingw** [comment]
Also update the Windows installer and I will attach it to the 2.0.1 release.

**Comment by mathiascode** [comment]
Alright, updating the installer.

**Comment by mathiascode** [comment]
Updated Windows installer: https://github.com/mathiascode/nicotine-plus/blob/993912ee5c8d8314a68c2d70f53053d4436cf68b/files/windows/Nicotine+-2.0.1.exe?raw=true

**Comment by mathiascode** [comment]
@kiplingw Can you update the title of the Github 2.0.1 release to "2.0.1"?
s

**Comment by kiplingw** [comment]
Done.

**Pull request merged**
