### PR TITLE
Don't include tests in packages

### PR DESCRIPTION
**Pull request by mathiascode**
I received a heads-up about test files being included in the final packages, when they shouldn't be. This PR prevents it from happening.

### CODE REVIEW

**Comment by kiplingw** [comment]
Mat, when you say don't include tests in the package, do you mean don't ship them in the upstream tarball or do you mean as part of the installed binary package?

**Comment by mathiascode** [comment]
Installed binary package. I think the debs already have some automatic filtering, but the "test" directory was installed to site-packages when using "python setup.py install" or a Fedora package at least.

**Comment by kiplingw** [comment]
Hmm, I'm not seeing it in the binary package:

```
$ apt-cache show nicotine
Package: nicotine
Priority: optional
Section: net
Installed-Size: 9094
Maintainer: Kip Warner <kip@thevertigo.com>
Architecture: all
Version: 1.4.3-202006172247~ubuntu20.04.1
Recommends: gir1.2-appindicator3-0.1, gir1.2-gsound-1.0, gir1.2-gspell-1, gir1.2-notify-0.7, python3-miniupnpc
Depends: python3:any, python3-miniupnpc | miniupnpc (>= 1.9), gobject-introspection, gir1.2-gtk-3.0, python3 (>= 3.5), python3-dbus, python3-gi, python3-mutagen (>= 1.25), xdg-utils
Filename: pool/main/n/nicotine/nicotine_1.4.3-202006172247~ubuntu20.04.1_all.deb
Size: 1206912
MD5sum: df5c59de0c06920f9dc15cfeae01f226
SHA1: b3e000052e0bc625314c33f0554ef0bad95f32f3
SHA256: ec074ee6b21ec73c33607bfb727c4375a3cc49456313efa791884355409e952a
Description-en: graphical client for SoulSeek P2P network (Gtk+ / Python 3)
 Nicotine+ is a client for SoulSeek, a light and efficient file sharing
 system, written in Python and using the GTK+ toolkit, based on the
 PySoulSeek project.
 .
 It features uploading, downloading, searching and chatting, with
 strict bandwidth control, and tries to look like PySoulSeek.
 .
 This package installs the Gtk+ 3 client which uses Python 3.
Description-md5: 6929ffc7fb523a5adbca8296feb1bb74

$ dpkg -L nicotine 
/.
/usr
/usr/bin
/usr/bin/nicotine
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/nicotine-1.4.3.egg-info
/usr/lib/python3/dist-packages/pynicotine
/usr/lib/python3/dist-packages/pynicotine/__init__.py
/usr/lib/python3/dist-packages/pynicotine/config.py
/usr/lib/python3/dist-packages/pynicotine/geoip
/usr/lib/python3/dist-packages/pynicotine/geoip/IP2Location.py
/usr/lib/python3/dist-packages/pynicotine/geoip/ipcountrydb.bin
/usr/lib/python3/dist-packages/pynicotine/gtkgui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/__init__.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/about.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/chatrooms.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/checklatest.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/countrycodes.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/dirchooser.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/downloads.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/entrydialog.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/fastconfigure.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/frame.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/imagedata.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/nowplaying.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/privatechat.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/search.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/settingswindow.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/transferlist.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/tray.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/buddylist.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/chatrooms.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/fastconfigure.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/mainwindow.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/nowplaying.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/privatechat.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/roomlist.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/search.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_AutoReplaceFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_AwayFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_BanFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_BloatFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_CensorFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_ChatFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_ColoursFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_CompletionFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_DownloadsFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_EventsFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_GeoBlockFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_IconsFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_IgnoreFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_LogFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_MiscFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_NotebookFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_PluginFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_PluginProperties.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_SearchFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_ServerFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_SharesFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_SoundsFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_TransfersFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_TreeView.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_UrlCatchFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/settingswindow_UserinfoFrame.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/userbrowse.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/ui/userinfo.ui
/usr/lib/python3/dist-packages/pynicotine/gtkgui/uploads.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/userbrowse.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/userinfo.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/userlist.py
/usr/lib/python3/dist-packages/pynicotine/gtkgui/utils.py
/usr/lib/python3/dist-packages/pynicotine/logfacility.py
/usr/lib/python3/dist-packages/pynicotine/metadata_mutagen.py
/usr/lib/python3/dist-packages/pynicotine/multiselect.py
/usr/lib/python3/dist-packages/pynicotine/pluginsystem.py
/usr/lib/python3/dist-packages/pynicotine/pynicotine.py
/usr/lib/python3/dist-packages/pynicotine/shares.py
/usr/lib/python3/dist-packages/pynicotine/slskmessages.py
/usr/lib/python3/dist-packages/pynicotine/slskproto.py
/usr/lib/python3/dist-packages/pynicotine/temporary.py
/usr/lib/python3/dist-packages/pynicotine/transfers.py
/usr/lib/python3/dist-packages/pynicotine/upnp.py
/usr/lib/python3/dist-packages/pynicotine/utils.py
/usr/share
/usr/share/applications
/usr/share/applications/org.nicotine_plus.Nicotine.desktop
/usr/share/doc
/usr/share/doc/nicotine
/usr/share/doc/nicotine/AUTHORS.md
/usr/share/doc/nicotine/NEWS.gz
/usr/share/doc/nicotine/PACKAGING.md
/usr/share/doc/nicotine/README.md.gz
/usr/share/doc/nicotine/RUNFROMGIT.md
/usr/share/doc/nicotine/SLSKPROTOCOL.md.gz
/usr/share/doc/nicotine/TODO.md
/usr/share/doc/nicotine/TRANSLATIONS.md
/usr/share/doc/nicotine/TRANSLATORS.md
/usr/share/doc/nicotine/changelog.Debian.gz
/usr/share/doc/nicotine/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/org.nicotine_plus.Nicotine.svg
/usr/share/locale
/usr/share/locale/da
/usr/share/locale/da/LC_MESSAGES
/usr/share/locale/da/LC_MESSAGES/nicotine.mo
/usr/share/locale/de
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/nicotine.mo
/usr/share/locale/es
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/nicotine.mo
/usr/share/locale/eu
/usr/share/locale/eu/LC_MESSAGES
/usr/share/locale/eu/LC_MESSAGES/nicotine.mo
/usr/share/locale/fi
/usr/share/locale/fi/LC_MESSAGES
/usr/share/locale/fi/LC_MESSAGES/nicotine.mo
/usr/share/locale/fr
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/nicotine.mo
/usr/share/locale/hu
/usr/share/locale/hu/LC_MESSAGES
/usr/share/locale/hu/LC_MESSAGES/nicotine.mo
/usr/share/locale/it
/usr/share/locale/it/LC_MESSAGES
/usr/share/locale/it/LC_MESSAGES/nicotine.mo
/usr/share/locale/lt
/usr/share/locale/lt/LC_MESSAGES
/usr/share/locale/lt/LC_MESSAGES/nicotine.mo
/usr/share/locale/nl
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/nicotine.mo
/usr/share/locale/pl
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/nicotine.mo
/usr/share/locale/pt_BR
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/nicotine.mo
/usr/share/locale/sk
/usr/share/locale/sk/LC_MESSAGES
/usr/share/locale/sk/LC_MESSAGES/nicotine.mo
/usr/share/locale/sv
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/nicotine.mo
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/nicotine.1.gz
/usr/share/metainfo
/usr/share/metainfo/org.nicotine_plus.Nicotine.appdata.xml
/usr/share/nicotine
/usr/share/nicotine/plugins
/usr/share/nicotine/plugins/README
/usr/share/nicotine/plugins/anti-shout
/usr/share/nicotine/plugins/anti-shout/PLUGININFO
/usr/share/nicotine/plugins/anti-shout/__init__.py
/usr/share/nicotine/plugins/examplars
/usr/share/nicotine/plugins/examplars/90-checkport.py
/usr/share/nicotine/plugins/examplars/README
/usr/share/nicotine/plugins/leech_detector
/usr/share/nicotine/plugins/leech_detector/PLUGININFO
/usr/share/nicotine/plugins/leech_detector/__init__.py
/usr/share/nicotine/plugins/memory_debugger
/usr/share/nicotine/plugins/memory_debugger/PLUGININFO
/usr/share/nicotine/plugins/memory_debugger/__init__.py
/usr/share/nicotine/plugins/multipaste
/usr/share/nicotine/plugins/multipaste/PLUGININFO
/usr/share/nicotine/plugins/multipaste/__init__.py
/usr/share/nicotine/plugins/np_xmplay_windows
/usr/share/nicotine/plugins/np_xmplay_windows/PLUGININFO
/usr/share/nicotine/plugins/np_xmplay_windows/__init__.py
/usr/share/nicotine/plugins/np_xmplay_windows/xmplaynp.py
/usr/share/nicotine/plugins/plugindebugger
/usr/share/nicotine/plugins/plugindebugger/PLUGININFO
/usr/share/nicotine/plugins/plugindebugger/__init__.py
/usr/share/nicotine/plugins/reddit
/usr/share/nicotine/plugins/reddit/PLUGININFO
/usr/share/nicotine/plugins/reddit/__init__.py
/usr/share/nicotine/plugins/spamfilter
/usr/share/nicotine/plugins/spamfilter/PLUGININFO
/usr/share/nicotine/plugins/spamfilter/__init__.py
/usr/share/nicotine/plugins/testreplier
/usr/share/nicotine/plugins/testreplier/PLUGININFO
/usr/share/nicotine/plugins/testreplier/__init__.py
/usr/share/nicotine/sounds
/usr/share/nicotine/sounds/default
/usr/share/nicotine/sounds/default/details.txt
/usr/share/nicotine/sounds/default/license.txt
/usr/share/nicotine/sounds/default/private.wav
/usr/share/nicotine/sounds/default/room_nick.wav
/usr/share/nicotine/trayicons
/usr/share/nicotine/trayicons/trayicon_away.png
/usr/share/nicotine/trayicons/trayicon_connect.png
/usr/share/nicotine/trayicons/trayicon_disconnect.png
/usr/share/nicotine/trayicons/trayicon_msg.png
/usr/share/python3
/usr/share/python3/runtime.d
/usr/share/python3/runtime.d/nicotine.rtupdate
```

**Comment by mathiascode** [comment]
It was already removed from the Debian packages, probably some automatic cleanup, but I'm not sure. If you create an RPM with `python setup.py bdist_rpm` (without the changes in this PR), and inspect it, you will find the "test" directory.

**Comment by kiplingw** [comment]
My concern here is that the source tarball _should_ normally contain the tests. Although this is a Python project, with the GNU Coding Standards it's standard to have a make `distcheck` target that unpacks, compiles and runs all in tree unit tests from the tarball.

**Comment by mathiascode** [comment]
Tarballs still contain the tests, at least when you create it with `python setup.py sdist`

**Pull request merged**
