### PR TITLE
Explain underscores in translation strings.

### PR DESCRIPTION
**Pull request by hboetes**
After a discussion on IRC, we decided it's a good idea to explain the underscores a bit.

### CODE REVIEW

**Comment by slook** [comment]
Please consider removing "so it doesn't really matter what they are" from the sentence, because this gives the impression that no thought is required when testing for conflicts and ergonomics, whereas a lot of thought goes into making sure the mnemonics make sense. If anything, more emphasis is needed to highlight that it is important that they are properly tested.

**Comment by hboetes** [comment]
OK. Truth be told, I have no idea how to use the mnemonics. I'm looking forward to your proposal, please explain it as well as you can.

**Comment by slook** [comment]
The portion of a label that enables keyboard selection of a menu item or button is defined by an underscore character "_" before the mnemonic letter to be accessed with a keyboard accelerator, for example Alt+F for the native "_File" menu. It is important that selectable items within the same menu or interface area each have unique mnemonics to avoid any key conflicts that may cause navigation problems for users who are unable to use a mouse or other pointing device.

If possible, the first letter in the string will usually be the most ideal choice for a mnemonic key, but if that is already in use by a conflicting item then put the underscore in front of another letter that makes logical sense, and is easy for the user to remember whilst avoiding conflict or confusion with other mnemonic keys or shortcut keys that are used in the user interface. In some cases, the same letter may appear in your language string that is used in the English string, which may or not be appropriate.

**Comment by hboetes** [comment]
I just discovered that you can see the mnemonics if you press just the alt-key. =)

**Pull request merged**
