### PR TITLE
Fix error in tab visibility loop code

### PR DESCRIPTION
**Pull request by mathiascode**
- The loop should finish, not end abruptly.
- Cosmetics

### CODE REVIEW

**Comment by kiplingw** [comment]
@mathiascode, maybe easier to simply commit your changes and then push when you are ready. If you push every commit into GitHub the CI machines start grinding.

**Comment by mathiascode** [comment]
Probably a better idea.

**Comment by mathiascode** [comment]
Alright, no more commits to this PR. I'll stop myself before I go overboard.

**Comment by kiplingw** [comment]
You can certainly keep committing, but what I'm saying is push the commits when you're ready.

**Comment by mathiascode** [comment]
I know, I just want to stop pushing irrelevant changes to the PR before I clutter the differ too much. :) I think these were all the small things I noticed for now.

**Pull request merged**
