### PR TITLE
Change layout to improve rendering on main website's NEWS.html

### PR DESCRIPTION
**Pull request by hboetes**

### CODE REVIEW

**Comment by hboetes** [comment]
The introduction is rendered as a code block, it should be a normal paragraph.

https://nicotine-plus.github.io/nicotine-plus/NEWS.html

**Comment by kiplingw** [comment]
Rather than removing that block, can you simply change how it is rendered?

**Comment by hboetes** [comment]
Please check the diff again, I didn't remove any text, I removed the leading spaces so it will be indented like a paragraph.

**Comment by kiplingw** [comment]
Ah yes, you are right.

**Pull request merged**
